# Generated by Django 2.0.7 on 2018-07-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='github',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='github'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='qq'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='toutiao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='头条号'),
        ),
    ]
