# Generated by Django 2.0.7 on 2018-07-31 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180731_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Attachment', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='article',
            name='news_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='文章展示图片'),
        ),
    ]
