# Generated by Django 2.0.7 on 2018-08-01 14:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180731_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='Article/File/', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(max_length=10000, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='news_img',
            field=models.ImageField(blank=True, null=True, upload_to='Article/Img/', verbose_name='文章展示图片'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
