# Generated by Django 2.0.7 on 2018-08-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180801_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='download_times',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='下载次数'),
        ),
    ]
