# Generated by Django 2.0.7 on 2018-08-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_download_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='attachment',
            new_name='attachment_file',
        ),
    ]
