# Generated by Django 2.0.7 on 2018-08-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180801_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='attachment_file',
            new_name='attachment_id',
        ),
    ]
